### ISSUE TITLE
Register factory fixture name

### ISSUE THREAD

**Issue by jonjonw** [pytest-dev/pytest-factoryboy#102]
Could you provide a way to register a factory fixture with a different name?

Maybe something like `register(ExampleFactory, factory_name="my_example_factory")`

I tried the following but it still uses `example_factory` as the fixture name:
```
from myapp.factories import ExampleFactory as MyExampleFactory
register(MyExampleFactory)
```

**Comment by Korben11** [comment]
Use `_name`, worked out for me. Definition:
```py
def register(factory_class, _name=None, **kwargs):
    r"""Register fixtures for the factory class.
    ...
    """
```

**Comment by skarzi** [comment]
`_name` parameter of `register()` function is used to define model instance fixture name, so it doesn't solve @jonjonw issue.
Currently, fixture name is generated from `factory_class.__name__` (see [implementation](https://github.com/pytest-dev/pytest-factoryboy/blob/bb6508f9540472061b9e873f4c228ef2179b91b2/pytest_factoryboy/fixture.py#L151)) so it's impossible to set factory fixture name to a custom value, the only thing you can do is to subclass your `ExampleFactory` and then register it, e.g.:

```python
class MyExampleFactory(ExampleFactory):
    pass
    

register(ExampleFactory)  # creates `example_factory` and `example` fixtures
register(MyExampleFactory, _name='my_example')  # creates `my_example_factory` and `my_example` fixtures
``` 

Note that I have overridden the model fixture name (`_name`), if you skip this then the `example` model fixture will be generated by the last registered factory of this model.

**Comment by Korben11** [comment]
@skarzi Question was: *Could you provide a way to register a factory fixture with a different name?*. This is provided using `_name` argument.
```py
register(ExampleFactory, _name='my_example')  # creates `my_example_factory` and `my_example` fixture
```
The goal was to use a different fixture name, which is achieved.

**Comment by skarzi** [comment]
`register()` function creates 2 fixtures:

1. factory class fixture - auto-generated from `factory_class.__name__`
2. model instance fixture - custom value can be used by setting `_name` parameter

Maybe I am wrong, but I thought this issue is about using a custom name for the factory class (point 1.) fixture.

**Comment by Korben11** [comment]
My issue was with the auto-generated one from `factory_class.__name__`. I had a conflict having the same model name from another Django app. `drf_stripe.models.Account` & `second_app.models.Account`. Resolved it using `_name`. Now there's no conflict which means it either uses `factory_class.__name__` as default or `_name`. Each fixture and factory is now creating the correct class type.   

So function `register()` is creating only one fixture at a time.

**Comment by youtux** [comment]
I'll consider this solved then.
