### ISSUE TITLE
fixture 'author' not found

### ISSUE THREAD

**Issue by qari** [pytest-dev/pytest-factoryboy#12]
```python
import factory
from pytest_factoryboy import register

@register
class AuthorFactory(factory.Factory):

    class Meta:
        model = Author

    name = "Charles Dickens"


def test_model_fixture(author):
    assert author.name == "Charles Dickens"
```

Get error '"author" is not found', only works with author_factory

**Comment by olegpidsadnyi** [comment]
Please translate

**Comment by qari** [comment]
Get error '"author" is not found', only works with author_factory

**Comment by bubenkoff** [comment]
How do you run the test?

**Comment by olegpidsadnyi** [comment]
What is the exact error? There's is Author model is missing in your snippet. It works for me if you add it. The same code works in the tests of the library. See https://github.com/pytest-dev/pytest-factoryboy/blob/master/tests/test_factory_fixtures.py

**Comment by qari** [comment]
run test py.test
