### ISSUE TITLE
What am I missing in your integration?

### ISSUE THREAD

**Issue by jakobdo** [pytest-dev/pytest-factoryboy#129]
Hello,
I am trying this example: https://github.com/pytest-dev/pytest-factoryboy#integration

And in this test: 
```python
def test_book_factory(book_factory):
    ...
    assert isinstance(book_factory, BookFactory)
    ...
```

I am getting an error.
If I change to assert book_factory == BookFactory it works. But why is current version not working?

**Comment by skarzi** [comment]
hi :wave: 
There is an error in `README.md`, because `*_factory` fixtures return factory classes not its instances, so it should be:

```python
    assert book_factory is BookFactory
```
or you can eventually use `issubclass` function
