### ISSUE TITLE
@register decorator should accept parameters

### ISSUE THREAD

**Issue by youtux** [pytest-dev/pytest-factoryboy#137]
The `register` function, when used as decorator, should be able to accept parameters:

```python

@register("post_data", user=LazyFixture("http_user")
class SomePostDataFactory(...):
    ...
```

I think this can be easily done just like ptyest does it for the fixture decorator: https://github.com/pytest-dev/pytest/blob/eb8b3ad929cdbaf996be1bb16b37abd7762cceeb/src/_pytest/fixtures.py#L1231

**Comment by skarzi** [comment]
hi :wave: 

I can prepare a PR for this issue

**Comment by youtux** [comment]
That would be great, thanks!
