### ISSUE TITLE
Impossible to override create param for model fixture

### ISSUE THREAD

**Issue by Glueon** [pytest-dev/pytest-factoryboy#15]
Hi guys. Thanks for the work you've done. I use this project quite often and there is a little problem.

It's possible to pass in `create=True` param to `register` function to override default behavior of a factory fixture.

Unfortunately it does not affect a model fixture and it's impossible to override this behavior.  Quite often my tests need in-db model instance. Right now I need to do:

    def test_my_test(some_obj):
         some_obj.save()
         ...

This is a little be annoying and to me eliminates the benefit of that fixture. Because I can achieve the same goal with:

    def test_my_tests(some_obj_factory):
         some_obj = some_obj_factory() 

It would very convenient to be able not to call `save` each time before the test.

It is very strange why object is not saved in DB.

**Comment by Glueon** [comment]
Accidentally closed this issue. I use that in django project:

```
class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = settings.AUTH_USER_MODEL

    username = factory.Faker('user_name')

    @factory.post_generation
    def post(obj, create, extracted, **kwargs):
        obj.set_password('password')
```

If I use `user` fixture then the model object I get has pk but seems to be not in DB unless I explicitly call `user.save()`.


So this does not work:
```
def test_foo(user, client):
     client.login(username=user.username, password='password')
```

Unless I do:
```
def test_foo(user, client):
     user.save()
     client.login(username=user.username, password='password')
```

**Comment by thedrow** [comment]
Same question here.

**Comment by thedrow** [comment]
Seems possible but it's not implemented yet. See https://github.com/pytest-dev/pytest-factoryboy/blob/master/pytest_factoryboy/fixture.py#L174
How do you imagine this working?

**Comment by syradium** [comment]
It's interesting that the line you gave should actually call `build` or `create` based on strategy: https://github.com/rbarrois/factory_boy/blob/master/factory/base.py#L78

So this should work, but does not ...

**Comment by thedrow** [comment]
@syradium I think what the OP means is that you want to be able to override the default.

**Comment by syradium** [comment]
@thedrow  I am sorry, OP?

According to the line I gave `Factory()` call should take into account default strategy. I think it would sufficient if this fixture would take into account default strategy. And it does not. I tried to set `BUILD_STRATEGY` explicitly but still object isn't created.

In fact created object has a `pk`  but object does not exist in DB which is weird. So maybe Django/pytest-django does something unexpected.

**Comment by thedrow** [comment]
@syradium OP = Original Poster. The one who opened the issue.

**Comment by syradium** [comment]
@thedrow Oh, did not get that. Yeah, it's a separate issue maybe.

**Comment by olegpidsadnyi** [comment]
I'm not using Django ORM so I didn't realize that save is being called on the postgen hook. I have to think how to invoke it since all post-gens are deferred

**Comment by olegpidsadnyi** [comment]
@Glueon I've added support of the _after_postgeneration hook. Could you try if it works for you now in the branch of the PR #22?
