### ISSUE TITLE
py.text --fixture produces unorderable types: module() < str()

### ISSUE THREAD

**Issue by friendlyG0688** [pytest-dev/pytest-factoryboy#17]
In conftest.py I am registering factory classes from the django ORM factoryboy base class

I am importing register by
"from pytest_factoryboy import register"  [I have found that it matters]

This issue occurs on either of the two below as the factory class:
factory.Factory or factory.djangoORM...Factory (sorry can't remember)

To produce error:
Running the command 
"py.test --fixtures DIRECTORY"
where DIRECTORY is folder containing pytest.ini & manage.py

That command lists the fixtures available for the test configuration.

That command produces: "unorderable types: module() < str()"

I traced it back through and by modifying 
pytest_factorboy\fixture.py

in the make_fixture function where it was
fixture_func.__module__ = module
I changed it to
fixture_func.__module__ = str(module)

and all the fixtures were listed properly, but the fixtures I registered through pytest_factoryboy had the fixture module grouping in "c:\folder\folder\conftest.py"

I then changed it to 
fixture_func.__module__ = os.path.basename(module.__path__[0])

or sorry something like it, but gave it the base filename of conftest
fixture_func.__module__ = "conftest"

and the fixtures were grouped in the correct location with py.test --fixtures

Django is amazing
factoryboy is great
py.test is wonderful
& 
pytest_factoryboy is a must have!  Thank you all for the work you do!

Successfully just had world class Test Driven Development today with what I consider good tests.  Implementing your library was a very good call....

**Comment by olegpidsadnyi** [comment]
Indeed the __module__ is a module.__name__. Thanks
