### ISSUE TITLE
Ship tests with source distribution

### ISSUE THREAD

**Issue by mekanix** [pytest-dev/pytest-factoryboy#170]
As a port/package maintainer on FreeBSD I can run tests with other system installed packages, so it would be really helpful in early detection of errors/bugs on this platform. Would you please consider shipping them with source distribution? Thank you!

**Comment by youtux** [comment]
Hi @mekanix , I don't think I'll do it. It's not a best practice to package tests in the distribution, and with the current setup they would go in a directory that is not in the pytest_factoryboy namespace, which is not good at all.
You should consider checking out the whole repo if you need to run the test suite.
