### ISSUE TITLE
function uses no argument

### ISSUE THREAD

**Issue by ramast** [pytest-dev/pytest-factoryboy#171]
I've followed the documentation to make a simple test case

```
@pytest.mark.django_db(transaction=True)
@pytest.mark.parametrize("user__is_superuser", [True, False])
def test_custom_user_repr(user):
    if user.is_superuser:
        assert user.username == "[ADMIN ] user_1"
    else:
        assert user.username == "user_1"
```

This test case fails with error: `In test_custom_user_repr: function uses no argument 'user__is_superuser'`

However if I update the function definition to be

```
def test_custom_user_repr(user, user__is_superuser):
```

It works fine and test case passes.

But documentation gives this example which didn't involve accepting `author__name` as function paramter
```
@pytest.mark.parametrize("author__name", ["Bill Gates"])
def test_model_fixture(author):
    assert author.name == "Bill Gates"
```

## Package version
```
pytest==7.1.2
factory-boy==3.2.1
pytest-factoryboy==2.5.0
```

## Factoryboy class definition

```
class CustomUserFactory(DjangoModelFactory):

    class Meta:
        model = "accounts.CustomUser"
```

## conftest.py

```
register(CustomUserFactory, _name="user")
```

**Comment by youtux** [comment]
Hi, your CustomUserFactory does not define the is_superuser attribute, that’s why.
