### ISSUE TITLE
DeprecationWarning with pytest 7.2.0

### ISSUE THREAD

**Issue by GergelyKalmar** [pytest-dev/pytest-factoryboy#179]
```
pytest.PytestDeprecationWarning: The hookimpl pytest_runtest_call uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
 at .../lib/python3.8/site-packages/pytest_factoryboy/plugin.py:113
```

Refers to this line: https://github.com/pytest-dev/pytest-factoryboy/blob/master/pytest_factoryboy/plugin.py#L113

**Comment by GergelyKalmar** [comment]
@youtux Thank you very much! Would that be a huge favor to ask for a smaller release to get this out on pypi? I'm kind of blocked by this for the new release of https://github.com/logikal-io/pytest-logikal. Thank you in any case :).

**Comment by youtux** [comment]
I’ll try to make a release this week.

**Comment by youtux** [comment]
version 2.5.1 is out

**Comment by GergelyKalmar** [comment]
Thank you! I really appreciate it, we were able to make a new release too :tada:.
