### ISSUE TITLE
Feature request: override name of factory fixture?

### ISSUE THREAD

**Issue by WilliamDEdwards** [pytest-dev/pytest-factoryboy#191]
With `register(_name=...)`, the name of model fixtures can be overridden.

The same should be possible for factory fixtures.

**Comment by youtux** [comment]
Hey, sorry for getting back to this so late. Can you describe your use case, so that we can determine how to proceed? I was actually thinking of removing the generation of factory fixture altogether because I couldn't see a use case, so I'd be please to hear yours!

**Comment by skarzi** [comment]
I think what @WilliamDEdwards mean is that sometimes it's useful to have the same factory, but with some different default keyword argument registered as multiple fixtures, e.g.:

```python
register(AuthorFactory, _name="male_author", gender="M", name="John Doe")
register(AuthorFactory, _name="female_author", gender="F")
```

It will be nice to have separate fixtures generated for both `register` calls, e.g. `female_author_factory` and `male_author_factory`, so we can add `_factory_name` to the `register` parameters:

```python
register(AuthorFactory, _name="male_author", _factory_name="male_author_factory", gender="M", name="John Doe")
register(AuthorFactory, _name="female_author", _factory_name="female_author_factory", gender="F")
```

and then use `_factory_name` [here](https://github.com/pytest-dev/pytest-factoryboy/blob/118b71239dcea94eb20a86f15f2144c2651fac80/pytest_factoryboy/fixture.py#L121C51-L122C9): 

```python
factory_name = _factory_name or get_factory_name(factory_class)
```

**Comment by youtux** [comment]
If a user needs to specialize the factory, they can simply do that via inheritance:

```python
from test import factories

@register(_name="male_author")
class MaleAuthorFactory(factories.AuthorFactory):
    gender = "M"
    name="John Doe"

@register(_name="female_author")
class FemaleAuthorFactory(factories.AuthorFactory):
    gender = "F"
```
