### ISSUE TITLE
register with type hints

### ISSUE THREAD

**Issue by Eraldo** [pytest-dev/pytest-factoryboy#194]
## Issue / Reproduction

Given a registered user factory:
```py
register(UserFactory)
```

With this I can set parameters as expected:
```py
@pytest.mark.parametrize("user__name", ["Test User"])
def test__should_accept_params(user):
    assert user.name == "Test User"
```
=> Nicely accepts parameters, however it does not give me autocompletion in my IDE. 😞 

If I add an explicit fixture, I do get type hints as expected in my tests:
```py
@pytest.fixture
def user(user) -> User:
    return user

def test_should_autocomplete_in_ide(user):
    assert user.name == "Test User"  # user.<< I get IDE autocompletion for the User model fields.
```
=> If I don't add that specific feature, I do not get autocompletion in PyCharm when using only the register method.

However if I do create an explicit fixture like that to get autocompletion, I loose the option to set parameters on the factory. 😞 
```py
@pytest.mark.parametrize("user__name", ["Test User"])
def test__should_keep_ide_autocomplete(user):
    assert user.name == "Test User"  # Error: "In test__should_keep_ide_autocomplete: function uses no argument 'user__name'"
```

## Expected/desired behaviour.

Getting type hints in my tests while still being able to supply parameters to the factories without having to directly use the factories instead.

## Solution ideas

**Register decorator on fixture**
Creating an explicit fixture using @pytest.fixture AND adding the @register on it as well to get both type hints and allow pytest to pick up on the definition in my code.
```py
# Pseudo code.
@pytest.fixture
@register(factory = UserFactory)
def user(user) -> User:
    return user
```

**Rename params in sub-fixture.**
Allowing to rename/reuse the fixture parameters in my explicit override?
```py
# Pseudo code.
@pytest.fixture
@use_params(user)
def user(user) -> User:
    return user
```

**Pure Magic.**
Add some generic type hints magic so that it magically works (just kidding - Not very helpful as I have no idea how.)

## Notes

Perhaps I'm also just doing something wrong and there is an easier, better way of doing the same thing. 😅 
Any feedback and other ideas are very welcome. 🙏

**Comment by youtux** [comment]
If you want to use typing support, you can just add type annotations to your test functions:

```python

def test_should_autocomplete_in_ide(user: User):
    assert user.name == "Test User"

```

**Comment by Eraldo** [comment]
> If you want to use typing support, you can just add type annotations to your test functions:
Yes, you are absolutely right that I could add the hints to every test. I was hoping to avoid that.
I am already spoiled by pytest that it automatically injects/infers the correct type for me. It feels like a step back. 🙈 
Still you're correct.

**Comment by youtux** [comment]
I think this is more about individual IDEs code completion abilities. If you just use a "standard" type checker (e.g. mypy, pyright, ...) it wouldn't even try to figure out the type of the arguments, since that's not the idea of these tools.

I guess that one can write a mypy plugin that tries to determine the type of fixture arguments, but I don't think you can ever get to a complete result, given the "dynamicity" of pytest fixtures.
