### ISSUE TITLE
Request other fixtures in fixtures generated by register

### ISSUE THREAD

**Issue by sullivan-sean** [pytest-dev/pytest-factoryboy#201]
I'd like support for including other fixtures as dependencies for the fixtures generated by `pytest-factoryboy`

I'm using https://github.com/pytest-dev/pytest-django. This library requires that tests/fixtures that operate on the DB request their `db` fixture to ensure DB operations can be put in transactions. If this fixture is not included for a DB operation, that operation cannot be rolled back after a test is complete and the result of the operation will persist in the DB across other tests.

```
register(UserFactory, request_fixtures=['db'])
```

which would output a `user_factory()` fixture that requests the `db` fixture from `pytest-django`.

---

Without this feature, the option to use these two libraries together are very limited. I could either
1. Give up the assumption that the DB is clean/in some known state at the start of each test OR
2.  add the `db` fixture into any other fixture/test that relies on a factory fixture generated by `pytest-factoryboy`

My team heavily relies on the assumption of clean DB state so that, e.g. tests can be run in different orders, etc. So giving up 1 is not an acceptable solution. 2 is cumbersome and error prone: if a developer forgets to add the `db` fixture for a single test, it breaks the assumption from 1 and we again run into weird, unexpected issues where tests will fail if run in different orders, or if all/part of the test suite is run

**Comment by sullivan-sean** [comment]
Added a PR to showcase one approach to this, a different approach that would also solve at least my use case would be to add some way to set global fixtures that every `pytest-factoryboy` should request.

This would avoid having to list the requested fixtures on every `register` call, but would be less flexible/customizable for a use case where only certain factories should include the requested fixtures (e.g. if you are using `pytest-django` with `pytest-factoryboy` but area also using `pytest-factoryboy` for other factory fixtures that do not require the `db` and you'd like to avoid the inefficiency of including the `db` in all factory fixtures)

**Comment by youtux** [comment]
have you considered using `pytest.mark.django_db` in the test functions/modules/packages that require DB access?
The db fixture/ django_db marker was made on purpose so that you wouldn't accidentally hit the database in your test, requiring you to explicitly declare that your tests need db access.

You could also decide to make the `db` fixture an `autouse=True`, basically disabling this mechanism and allowing any test to access the DB. After all, adding the `db` fixture to the models is not that different form just making it an autouse fixture, since it will allow all factories to communicate to the DB anyway.

**Comment by sullivan-sean** [comment]
I'd like to do this at registration time for factoryboy fixtures that are factories for our DB models, since these are always used to create new instances in the DB (https://github.com/pytest-dev/pytest-factoryboy/pull/84) and always need DB access. We don't have any tests that rely on factoryboy fixtures but don't instantiate the model.

For us it is a little different from autouse since we don't construct all of our DB objects with factoryboy. Without our multitenancy setup, it is more expensive to have the DB request so we would like to avoid it when not necessary.

I like [your solution mentioned in the PR](https://github.com/pytest-dev/pytest-factoryboy/pull/202#issuecomment-1675754819), namely:

```python
def user_factory(db):
    return UserFactory

register(UserFactory)
```

which is already possible in pytest-factoryboy but undocumented.  It seems like this also addresses the request in https://github.com/pytest-dev/pytest-factoryboy/issues/100. Linking here in case somebody ends up on that thread.
