### ISSUE TITLE
Question regarding of usage of LazyFixture in @pytest.mark.parametrize on alias instead of chained fixture.

### ISSUE THREAD

**Issue by NT-Timm** [pytest-dev/pytest-factoryboy#209]
Is it not possible to use parametrize in this way?

Where banana, apple and peas are generated by registration through using a ProductFactory
And granny, friend and me are generated by registration through using a ConsumerFactory

```python
    @pytest.mark.parametrize(
        "fruit,eater",
        [
            pytest.param(LazyFixture("banana"), LazyFixture("granny")),
            pytest.param(LazyFixture("apple"), LazyFixture("friend")),
            # Vegetables are not allowed
            pytest.param(LazyFixture("peas"), LazyFixture("me"), marks=pytest.mark.xfail),
        ],
    )
    def test_eat_fruit(self, fruit, eater):
        assert eater.eat_fruit(fruit)
```

`eat_test.py::test_eat_fruit[None-fruit0-eater0] - AttributeError: 'LazyFixture' object has no attribute 'eat_fruit'`

In the code the LazyFixtures aren't resolved into actual objects.

**Comment by youtux** [comment]
This is really a pytest question, not something of pytest-factoryboy. You may want to try out [indirect parametrization](https://docs.pytest.org/en/7.1.x/example/parametrize.html#indirect-parametrization), or use `lazy_fixture` from https://github.com/tvorog/pytest-lazy-fixture instead
