### ISSUE TITLE
Broken support for Python 3.7

### ISSUE THREAD

**Issue by AWhetter** [pytest-dev/pytest-factoryboy#214]
I'm unlucky enough to still need to make use of Python 3.7. Our Python 3.7 test suites are failing because pytest-factoryboy is importing `importlib.metadata`, however that library was added in Python 3.8.

I see Python 3.7 support was dropped in v2.6.0, however the project.toml still specifies `python = ">=3.7"`. Please could that be updated, and v2.6.1 yanked from pypi so that pip does not pick up this broken release when running in Python 3.7.

**Comment by youtux** [comment]
I just published version 2.7.0. I won't yank 2.6.1, as it's a working build, just like 2.6.0.
