### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by raayu83** [pytest-dev/pytest-factoryboy#221]
I get the following DepractionWarnings when using pytest-factoryboy:

```
Lib\site-packages\factory\django.py:181: DeprecationWarning: ReportGroupFactory._after_postgeneration will stop saving the instance after postgeneration hooks in the next major release.
  If the save call is extraneous, set skip_postgeneration_save=True in the ReportGroupFactory.Meta.
  To keep saving the instance, move the save call to your postgeneration hooks or override _after_postgeneration.
```
I assume these come from pytest-factoryboy?

**Comment by kingbuzzman** [comment]
> I assume these come from pytest-factoryboy?
It does not. This comes from [factory-boy](https://github.com/FactoryBoy/factory_boy/blob/master/factory/django.py#L182)

**Comment by youtux** [comment]
well, yes, pytest-factoryboy calls the factories you define.
