### ISSUE TITLE
What happened to the docs?

### ISSUE THREAD

**Issue by asfaltboy** [pytest-dev/pytest-factoryboy#34]
I tried to look at the source (for a PR) by clicking "view source" in [rtd.io][1], however has stumbled into a 404 here: https://github.com/pytest-dev/pytest-factoryboy/blob/master/index.rst.

The [rtd build job][2] also fails for apparently the same reason.

[1]: http://pytest-factoryboy.readthedocs.io/en/latest/
[2]: https://readthedocs.org/projects/pytest-factoryboy/builds/4527380/

**Comment by bubenkoff** [comment]
thanks for noticing - should be fixed now

**Comment by asfaltboy** [comment]
Looks legit thanks! No PR is necessary "parameterize" typo is already fixed :)
