### ISSUE TITLE
Allow passing fixtures that pytest-factory's fixtures should depend on

### ISSUE THREAD

**Issue by underyx** [pytest-dev/pytest-factoryboy#37]
I have the following fixtures:

```python
@pytest.yield_fixture(scope='session')
def db_url():
    with testing.postgresql.Postgresql() as db:
        yield db.url()


@pytest.yield_fixture
def db(db_url):
    """Create a database session."""
    engine = sqlalchemy.create_engine(db_url)

    models.metadata.create_all(engine)

    factories.Session.configure(bind=engine)
    session = factories.Session()  # creates the thread local session used by factories
    yield session
    session.rollback()
    factories.Session.remove()  # disables the thread local session

    models.metadata.drop_all(engine)


pytest_factoryboy.register(factories.BookFactory)
```

My problem now is that trying to use the `book_factory` fixture on its own doesn't work; I need the `db` fixture to open a session the factory can use, first.

I'd like to be able to specify something like

```python
pytest_factoryboy.register(factories.BookFactory, depends_on=['db'])
```

which would have the same effect as the manual implementation of

```python
def book_factory(db):
    # …
```

would.

**Comment by bubenkoff** [comment]
can't you just use autouse fixture for that?
and then separate db related tests via package so then fixture will be used only for tests using it

**Comment by underyx** [comment]
@bubenkoff I was thinking of trying it but

1. I'm worried about the order, is it always going to run first?
2. I'm not sure how viable the package separation is, we have a few beastly functions which access up to five databases.

**Comment by bubenkoff** [comment]
to be sure about the order you do need to explicitly declare that - i agree, so avoiding it is better
but autouse fixtures always go before the explicitly used ones

**Comment by olegpidsadnyi** [comment]
What kind of the base class are you using for your factories?
I'm using SQLAlchemy, so it is lazily bound to the same session maker that my test setup is using.

In what way your factory is storing the model? Basically what ORM are you using?

**Comment by bubenkoff** [comment]
@underyx this looks like very big overhead
```
@pytest.yield_fixture(scope='session')
def db_url():
    with testing.postgresql.Postgresql() as db:
        yield db.url()
```

i would expect db to be session scoped, then making it autouse is efficient

**Comment by underyx** [comment]
>@underyx What kind of the base class are you using for your factories?

@olegpidsadnyi: `factory.alchemy.SQLAlchemyModelFactory`

I'm using SQLAlchemy as well — the `factories.Session` in the issue description's code is an SQLAlchemy `scoped_session`.

**Comment by bubenkoff** [comment]
@underyx doing `models.metadata.create_all(engine)` on every test if very inefficient
i would invest time in making tests isolated still, but sharing the same database during the whole session.
The way we do it is normally via randomization, using https://pypi.python.org/pypi/Faker
there's a plugin as well for it's integration `pytest-faker`

**Comment by underyx** [comment]
@bubenkoff well, alright, we have everything configured now with `autouse=True` and it works. But it's still not ideal that any test run will automatically create all databases even when I run tests that don't need any database at all. Any chance of this feature making it into pytest-factoryboy?

**Comment by olegpidsadnyi** [comment]
@underyx At this point I don't see it is coming. It would be yet another magical point of declaring a dependency besides a factory class, fixture registration (partial specialization), fixture propagation via conftest.py and finally the @pytest.mark.parametrize.
This would be just an invitation to start abusing it when there are decent ways to configure the test suite.
