### ISSUE TITLE
Function "getfuncargvalue" is deprecated.

### ISSUE THREAD

**Issue by YukSeungChan** [pytest-dev/pytest-factoryboy#41]
Hello,

I use pytest == 3.1.0 and get this warning:
DeprecationWarning: use of getfuncargvalue is deprecated, use getfixturevalue

**Comment by olegpidsadnyi** [comment]
Do you mind creating a PR with the compatibility fix?

**Comment by joshcrim** [comment]
Submitted PR to fix this: https://github.com/pytest-dev/pytest-factoryboy/pull/49

**Comment by olegpidsadnyi** [comment]
Since there were incompatible changes in FactoryBoy I decided to do a major release (2.0.1). I also took the opportunity to get rid of the pytest magic, so now it works with pytest>=3.3.2 without those fallbacks.
Thanks for the effort though.
