### ISSUE TITLE
Fixture has model_facotry should be model_factory

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest-factoryboy#43]
This really puzzled me. It's a typo and probably and easy fix.

**Comment by olegpidsadnyi** [comment]
@thedrow where do you see it?

**Comment by thedrow** [comment]
When you ask for a model_factory fixture you get fixture not found.
You can reproduce this by registering a factory and asking for it:
```
@register
class SomeFactory(factory.Factory):
  class Meta:
    model = SomeModel

def test_foo(some_factory):
  pass
```
If you ask for a some_facotry fixture instead you get the factory fixture.

**Comment by olegpidsadnyi** [comment]
There's a test for it https://github.com/pytest-dev/pytest-factoryboy/blob/master/tests/test_factory_fixtures.py#L100

**Comment by olegpidsadnyi** [comment]
@thedrow   def test_factory(book_facotry):
E       fixture 'book_facotry' not found

**Comment by thedrow** [comment]
I'll provide a test case in a PR.

**Comment by thedrow** [comment]
I can confirm that this doesn't always happen.
This is the output of `pytest --fixtures`:
```
--------------------------------------------------------------------------------------- fixtures defined from tests.conftest ---------------------------------------------------------------------------------------
agent
    <string>:3: no docstring available
agent_facotry
    <string>:3: no docstring available
organization
    <string>:3: no docstring available
organization__enrollment_secret
    <string>:3: no docstring available
organization__name
    <string>:3: no docstring available
organization_facotry
    <string>:3: no docstring available
scheduled_query
    <string>:3: no docstring available
scheduled_query__agent
    <string>:3: no docstring available
scheduled_query__interval
    <string>:3: no docstring available
scheduled_query__query
    <string>:3: no docstring available
scheduled_query__query_name
    <string>:3: no docstring available
scheduled_query_factory
    <string>:3: no docstring available
```

The agent factory and the organization factory are misspelled but the scheduled query factory isn't.

**Comment by olegpidsadnyi** [comment]
@thedrow and if you search for "facotry" through your codebase?

**Comment by thedrow** [comment]
@olegpidsadnyi Right. That was the problem.
