### ISSUE TITLE
Test star imports in conftest.py

### ISSUE THREAD

**Issue by MRigal** [pytest-dev/pytest-factoryboy#55]
Hi all,

When you have a project with many apps and many factories, you may not want to import them all explicitely in the conftest.py. So you import them with a star per package. (in general not a good practice)

IMHO, it would be great if pytest-factoryboy could emit an error for clashing names, rather than silently ignoring/overwriting them.

Thanks for the great work else!

**Comment by youtux** [comment]
Hi that's not really something that pytest-factoryboy can do (this is just how python works).
You could make your own import function that check for such clashes though.
