### ISSUE TITLE
DeprecationWarning: use of getfuncargvalue is deprecated, use getfixturevalue

### ISSUE THREAD

**Issue by villlem** [pytest-dev/pytest-factoryboy#68]
With pytest 3.8 using pytest-factoryboy starts producing

```
/.../python3.6/site-packages/pytest_factoryboy/plugin.py:107: DeprecationWarning: getfuncargvalue is deprecated, use getfixturevalue
  factoryboy_request = request.getfuncargvalue("factoryboy_request")
```
Here (https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning) is chagne in pytest that make this issue visible again, but its till there.

This is similar/same issue as #41 . Even after rewrite latest pytest-factoryboy still uses `getfuncargvalue` in `pytest_factoryboy/plugin.py` lines 73 and 107.

If this is not intentional can prepare PR to fix this.

**Comment by youtux** [comment]
I think it is time to require pytest>=3.0.0 and switch to getfixturevalue. Feel free to make a PR, @villem.

**Comment by krnr** [comment]
still got this warning with 

```
factory-boy==2.11.1
pytest-factoryboy==2.0.1
pytest==3.8.2
```

**Comment by azie-ginanjar** [comment]
its resolved with
`factory-boy==2.11.1
pytest-factoryboy==2.0.2`

**Comment by TheBubblePopped** [comment]
Sadly not for me
