### ISSUE TITLE
CI is failing since pytest-cov is not pegged and requires pytest > 3.6

### ISSUE THREAD

**Issue by asfaltboy** [pytest-dev/pytest-factoryboy#79]
As seen in travis fails here:
https://travis-ci.org/pytest-dev/pytest-factoryboy/jobs/552058354

Support drop of pytest < 3.6 is mentioned in pytest-cov release notes here: https://github.com/pytest-dev/pytest-cov/blob/master/CHANGELOG.rst#260-2018-09-03

We can either peg pytest-cov in our https://github.com/pytest-dev/pytest-factoryboy/blob/fca00b664bbc8ba238ab500612080cd11a94dcb8/requirements-testing.txt#L3 to e.g `pytest-cov<2.6` ; or, we can drop support for pytest < 3.6 as well, in our travis/tox configurations.

Since last release was a while ago, I lean towards the latter, with a 2.1 release noting this breaking change.

What say you @pytest-dev ?

**Comment by youtux** [comment]
Fixed in #80, now we test only with pytest >= 3.6
