### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by drewrisinger** [pytest-dev/pytest-factoryboy#92]
While reviewing https://github.com/NixOS/nixpkgs/pull/89248, I found that this project claims the MIT license but doesn't include the MIT license text in the repository anywhere. Best practice is to include the license along with your source code. To remedy, follow the steps listed: https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/ (Heading: ``Applying a license to your open source projects``)

**Comment by symonk** [comment]
Good spot! Thanks for logging - will fix this evening
