### ISSUE TITLE
How to create two fixtures with shared value from a subfactory?

### ISSUE THREAD

**Issue by barraponto** [pytest-dev/pytest-factoryboy#99]
This project has two factories using a third factory as subfactory -- both User and Location have `company` as a Company subfactory. How can i get both `user` and `location` as fixtures with the same `company` instance?

```python
class CompanyFactory(FlaskSQLAlchemyModelFactory):
    """Create companies and optionally save them to the database."""

    class Meta:  # noqa: D106
        model = Company


class LocationFactory(FlaskSQLAlchemyModelFactory):
    """Create location and optionally save them to the database."""

    class Meta:  # noqa: D106
        model = Location

    label = TEST_LABEL
    company = factory.SubFactory(CompanyFactory)


class UserFactory(FlaskSQLAlchemyModelFactory):
    """Create users and optionally save them to the database."""

    class Meta:  # noqa: D106
        model = User

    company = factory.SubFactory(CompanyFactory)
```

**Comment by youtux** [comment]
did you try
```python
register(CompanyFactory)
register(LocationFactory)
register(UserFactory)
```
?

**Comment by barraponto** [comment]
Of course. But if my test requires both `location` and `user`, both will have different companies.

**Comment by youtux** [comment]
They should get the same company. Can you post an minimal example to reproduce the issue?

**Comment by barraponto** [comment]
OMG you're right! I just assumed they weren't!
Subfactories are only called once then, unless I somehow ask it not to?

**Comment by youtux** [comment]
UserFactory will use the `company` fixture when creating a user. That `company` fixture is registered by `register(CompanyFactory)`.

If you want to use a different company for your user, you have to override the fixture or use an explicit pytest parametrization (pytest.mark.parametrize):

```python
register(CompanyFactory)  # Implicitly registered under the "company" fixture name
register(CompanyFactory, "second_company")

register(LocationFactory)
register(UserFactory)

@pytest.mark.parametrize('user__company', [LazyFixture("second_company"))
def test_foo(user, company, second_company):
    assert user.company is second_company
```
